config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  
  get 'home/about' => 'home#about'
  get 'search' => 'search#search'
  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'users/sessions'}
  resources :users do
  	resource :relationships, only: [:create, :destroy]
  	get 'follows' => 'relationships#follow', as: 'follows'
  	get 'followers' => 'relationships#follower', as: 'followers'
  end
  resources :books do
  	resources :favorites, only: [:create]
    delete 'favorites' => 'favorites#destroy'
  	resources :book_comments, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
	def search
		@user_or_book = params[:option]
		@how_search = params[:choice]
		if @user_or_book == "1"
			@users = User.search(params[:search], @user_or_book, @how_search)
		else
			@books = Book.search(params[:search], @user_or_book, @how_search)
		end
	end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/search.html.erb
<div class="body">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
			<% if @user_or_book == "1" %>
				<h1>Users search for '<%= params[:search] %>'</h1>
				<table class="table table-hover table-inverse">
					<thead>
						<tr>
							<th>Image</th>
							<th>Name</th>
							<th>Introduction</th>
							<th colspan="3"></th>
						</tr>
					</thead>
					<% @users.each do |user| %>
					<tbody>
						<tr>
							<td>
								<%= attachment_image_tag user, :profile_image, format: 'jpeg', size: "45x45", fallback: "no_image.jpg" %>
							</td>
							<td><%= user.name %></td>
							<td colspan="3"></td>
							<td><%= link_to "Show", user_path(user) %></td>
						</tr>
					</tbody>
					<% end %>
				</table>
			<% elsif @user_or_book == "2" %>
				<h1>Books search for '<%= params[:search] %>'</h1>
				<table class="table table-hover table-inverse">
					<thead>
						<tr>
							<th></th>
							<th>Title</th>
							<th>Opinion</th>
							<th></th>
							<th></th>
							<th colspan="3"></th>
						</tr>
					</thead>
					<tbody>
						<% @books.each do |book| %>
						<tr>
							<td>
								<%= link_to user_path(book.user) do %>
								<%= attachment_image_tag book.user, :profile_image, format: 'jpeg', size: "45x45", fallback: "no_image.jpg" %>
								<% end %>
							</td>
							<td><%= link_to "#{book.title}", book_path(book) %></td>
							<td><%= book.body %></td>
							<td>
								<% if book.favorited_by?(current_user) %>
							    	<%= link_to book_favorite_path(book, @user), method: :delete do %>
							    	<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
							    	<%= book.favorites.count %>
							    	<% end %>
							    <% else %>
							    	<%= link_to book_favorites_path(book), method: :post do %>
							    	<i class="fa fa-heart" aria-hidden="true" style="color: grey;"></i>
							    	<%= book.favorites.count %>
							    	<% end %>
							    <% end %>
							</td>
							<td>
								<i class="fa fa-comment"></i>
								<%= book.book_comments.count %>
							</td>
							<td colspan="3"></td>
						</tr>
						<% end %>
					</tbody>
				</table>
			<% end %>
		</div>
	</div>
</div>