config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  
  get 'home/about' => 'home#about'
  get 'search' => 'search#search'
  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'users/sessions'}
  resources :users do
  	resource :relationships, only: [:create, :destroy]
  	get 'follows' => 'relationships#follow', as: 'follows'
  	get 'followers' => 'relationships#follower', as: 'followers'
  end
  resources :books do
  	resources :favorites, only: [:create]
    delete 'favorites' => 'favorites#destroy'
  	resources :book_comments, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  validates :introduction, length: {maximum: 50}
  validates :name, length: {minimum: 2, maximum: 20}, presence: true


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower

  attachment :profile_image

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

  def User.search(search, user_or_book, how_search)
    if user_or_book == "1"
      if how_search == "1"
        User.where(['name LIKE ?', "%#{search}%"])
      elsif how_search == "2"
        User.where(['name LIKE ?', "#{search}%"])
      elsif how_search == "3"
        User.where(['name LIKE ?', "%#{search}"])
      elsif how_search == "4"
        User.where(['name LIKE ?', "#{search}"])
      else
        User.all
      end
    end
  end

  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController

  before_action :authenticate_user!
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  def after_sign_up_path_for(resource)
    user_path(resource)
  end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController

  before_action :authenticate_user!
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  def after_sign_in_path_for(resource)
    user_path(resource)
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  before_action :ensure_correct_user, {only: [:edit, :update]}

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
  	@book = Book.new
  end

  def index
  	@user = User.find(current_user.id)
  	@users = User.all
  	@book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       flash[:notice] = "You have updated user successfully."
       @user.save
       redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
  params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_info.html.erb
<div class="row">
			<div class="col-xs-3">
				<h2>User info</h2>
				<%= attachment_image_tag user, :profile_image, format: 'jpeg', size: "100x100", fallback: "no_image.jpg" %>
				<table class="table">
					<tr class="userinfo">
						<th>name</th>
						<th><%= user.name %></th>
					</tr>
					<tr class="userinfo">
						<th>introduction</th>
						<th><%= user.introduction %></th>
					</tr>
					<tr class="userinfo">
						<th>follows</th>
						<th><%= link_to user.follower.count, user_follows_path(user) %></th>
					</tr>
					<tr class="userinfo">
						<th>followers</th>
						<th><%= link_to user.followed.count, user_followers_path(user) %></th>
					</tr>
				</table>
				<% if current_user.id != user.id %>
					<% if current_user.following?(user) %>
						<%= link_to "フォロー外す", user_relationships_path(user), method: :delete, class: "btn btn-primary" %>
					<% else %>
						<%= link_to "フォローする", user_relationships_path(user), method: :post, class: "btn btn-success" %>
					<% end %>
				<% end %>
				<% if user.id == current_user.id %>
				<div class="row">
					<%= link_to "", edit_user_path(user), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
				</div>
				<% end %>

				<h2>New book</h2>
				<%= form_for (book) do |f| %>
				<div class="field row">
					<label>Title</label>
					<%= f.text_field :title, class:"col-xs-12" %>
				</div>
    			<div class="field row">
					<label>Opinion</label>
					<%= f.text_area :body, class:"col-xs-12" %>
				</div>
				<div class="row">
				<%= f.submit 'Create Book', class:"btn btn-primary col-xs-12" %>
				</div>
				<% end %>
			</div>

app/views/users/edit.html.erb
<div class="body">
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@user.errors.count, "error") %> prohibited this obj from being saved:</h3>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container">
    <h2>User info
    </h2>
    <%= form_for(@user) do |f| %>
      <div class="field">
        <label>name</label><br>
        <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
      </div>
      <div class="field">
        <label>image</label><br>
        <%= f.attachment_field :profile_image %>
      </div>
      <div class="field">
        <label>Introduction</label><br>
        <%= f.text_area :introduction %>
      </div>
      <div class="actions">
        <%= f.submit "Update User" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="body">
	<div class="container">
		<%= render 'users/info', user: @user, book: @book %>
			<div class="col-xs-9">
				<h2>Users</h2>
				<table class="table table-hover table-inverse">
					<thead>
						<tr>
							<th>image</th>
							<th>name</th>
							<th colspan="3"></th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						<% @users.each do |user| %>
						<tr>
							<td>
								<%= attachment_image_tag user, :profile_image, format: 'jpeg', size: "45x45", fallback: "no_image.jpg" %>
							</td>
							<td><%= user.name %></td>
							<td colspan="3"></td>
							<td><%= link_to "Show", user_path(user) %></td>
						</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="body">
 	<% if flash[:notice] %>
 	<div>
 		<%= flash[:notice] %>
 	</div>
 	<% end %>
	<div class="container">
		<%= render 'users/info', user: @user, book: @book %>
			<div class="col-xs-9">
				<h2>Books</h2>
				<table class="table table-hover table-inverse">
					<thead>
						<tr>
							<th></th>
							<th>Title</th>
							<th>Opinion</th>
							<th></th>
							<th></th>
							<th colspan="3"></th>
						</tr>
					</thead>
					<tbody>
						<% @books.each do |book| %>
						<tr>
							<td>
								<%= link_to user_path(book.user.id) do %>
								<%= attachment_image_tag @user, :profile_image, format: 'jpeg', size: "45x45", fallback: "no_image.jpg" %>
								<% end %>
							</td>
							<td><%= link_to "#{book.title}", book_path(book) %></td>
							<td><%= book.body %></td>
							<td id="favorite_button_<%= book.id %>">
								<%= render 'favorites/favorite', book: book %>
							</td>
							<td>
								<i class="fa fa-comment"></i>
								<%= book.book_comments.count %>
							</td>
							<td colspan="3"></td>
						</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>