config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  
  get 'home/about' => 'home#about'
  get 'search' => 'search#search'
  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'users/sessions'}
  resources :users do
  	resource :relationships, only: [:create, :destroy]
  	get 'follows' => 'relationships#follow', as: 'follows'
  	get 'followers' => 'relationships#follower', as: 'followers'
  end
  resources :books do
  	resources :favorites, only: [:create]
    delete 'favorites' => 'favorites#destroy'
  	resources :book_comments, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
	
	validates :title, presence: true
	validates :body, presence: true
	validates :body, length: {maximum: 200}

	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

	def Book.search(search, user_or_book, how_search)
		if user_or_book == "2"
			if how_search == "1"
				Book.where(['title LIKE ?', "%#{search}%"])
			elsif how_search == "2"
				Book.where(['title LIKE ?', "#{search}%"])
			elsif how_search == "3"
				Book.where(['title LIKE ?', "%#{search}"])
			elsif how_search == "4"
				Book.where(['title LIKE ?', "#{search}"])
			else
				Book.all
			end
		end
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!
  before_action :ensure_correct_book, {only: [:edit, :update, :destroy]}

  def index
  	@books = Book.all
    @user = User.find(current_user.id)
    @book = Book.new
  end

  def create
  	@book = Book.new(book_params)
    @book.user_id = current_user.id
    @user = User.find(current_user.id)
  	@books = Book.all
  	if @book.save
  		flash[:notice] = "You have creatad book successfully."
  		redirect_to book_path(@book.id)
  	else
  		render :index
  	end
  end

  def show
  	@book = Book.find(params[:id])
    @user = User.find(current_user.id)
    @book2 = Book.new
    @book_comment = BookComment.new
  end

  def edit
  	@book = Book.find(params[:id])
  end

  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		flash[:notice] = "You have updated book successfully."
  		redirect_to book_path(@book.id)
  	else
  		render :edit
  	end
  end

  def destroy
  	book = Book.find(params[:id])
  	book.destroy
  	redirect_to books_path
  end

  private

  def book_params
  	params.require(:book).permit(:title, :body, :user_id)
  end

  def ensure_correct_book
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_comment.html.erb
<tbody>
	<% book.book_comments.each do |book_comment| %>
	<tr>
		<td>
			<%= link_to user_path(book_comment.user) do %>
			<%= attachment_image_tag book_comment.user, :profile_image, format: 'jpeg', size: "45x45", fallback: "no_image.jpg" %>
			<br>
			<%= book_comment.user.name %>
			<% end %>
		</td>
		<td><%= book_comment.comment %></td>
		<td>
			<% if book_comment.user_id == current_user.id %>
			<%= link_to "Destroy", book_book_comment_path(book, book_comment), method: :delete, class:"btn btn-danger", remote: true %>
			<% end %>
		</td>
	</tr>
	<% end %>
</tbody>

app/views/books/edit.html.erb
<div class="body">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1>Editing Book</h1>
        <% if @book.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@book.errors.count, "error") %> prohibited this product from being saved:</h2>
              <ul>
                <% @book.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                  <% end %>
              </ul>

            </div>
        <% end %>
        <%= form_for (@book) do |f| %>
        	<div class="field row">
        		<label>Title</label>
        		<%= f.text_field :title, class:"col-xs-12" %>
        	</div>
          <div class="field row">
        		<label>Opinion</label>
        		<%= f.text_area :body, class:"col-xs-12" %>
        	</div>
          <div class="field row">
        	  <%= f.submit 'Update Book', class:"col-xs-12 btn btn-primary" %>
          </div>
        <% end %>
        <%= link_to "Show", book_path(@book.id) %> | <%= link_to "Back", books_path %>
      </div>
      <div class="col-md-3"></div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="body">
	<% if @book.errors.any? %>
    <div id="error_explanation">
      	<h3><%= pluralize(@book.errors.count, "error") %> prohibited this obj from being saved:</h3>
      	<ul>
       		<% @book.errors.full_messages.each do |message| %>
        	<li><%= message %></li>
        	<% end %>
      	</ul>
    </div>
	<% end %>
	<div class="container">
		<%= render 'users/info', user: @user, book: @book %>
			<div class="col-xs-9">
				<h2>Books</h2>
				<table class="table table-hover table-inverse">
					<thead>
						<tr>
							<th></th>
							<th>Title</th>
							<th>Opinion</th>
							<th></th>
							<th></th>
							<th colspan="3"></th>
						</tr>
					</thead>
					<tbody>
						<% @books.each do |book| %>
						<tr>
							<td>
								<%= link_to user_path(book.user) do %>
								<%= attachment_image_tag book.user, :profile_image, format: 'jpeg', size: "45x45", fallback: "no_image.jpg" %>
								<% end %>
							</td>
							<td><%= link_to "#{book.title}", book_path(book) %></td>
							<td><%= book.body %></td>
							<td id="favorite_button_<%= book.id %>">
								<%= render 'favorites/favorite', book: book %>
							</td>
							<td>
								<i class="fa fa-comment"></i>
								<%= book.book_comments.count %>
							</td>
							<td colspan="3"></td>
						</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

app/views/books/show.html.erb
<div class="body">
	<% if flash[:notice] %>
	<div>
		<%= flash[:notice] %>
	</div>
	<% end %>
	<div class="container">
		<%= render 'users/info', user: @book.user, book: @book2 %>
			<div class="col-xs-9">
				<h2>Book detail</h2>
				<table class="table table-hover table-inverse">
					<tbody>
						<tr>
							<td>
								<%= link_to user_path(@book.user) do %>
								<%= attachment_image_tag @book.user, :profile_image, format: 'jpeg', size: "45x45", fallback: "no_image.jpg" %>
								<br>
								<%= @book.user.name %>
								<% end %>
							</td>
							<td><%= link_to "#{@book.title}", book_path(@book) %></td>
							<td><%= @book.body %></td>
							<td id="favorite_button_<%= @book.id %>">
								<%= render 'favorites/favorite', book: @book %>
							</td>
							<td>
								<i class="fa fa-comment"></i>
								<%= @book.book_comments.count %>
							</td>
							<% if @book.user == current_user %>
							<td><%= link_to "Edit", edit_book_path(@book), class:"btn btn-success" %></td>
							<td><%= link_to "Destroy", book_path(@book), method: :delete, class:"btn btn-danger", "data-confirm" => "Are you sure?" %></td>
							<% end %>
						</tr>
					</tbody>
				</table>
			</div>
			<div class="col-xs-9">
				<table id="comment_<%= @book.id %>">
					<%= render 'comment', book: @book %>
				</table>
				<%= form_with model:[@book, @book_comment], data: {remote: true} do |f| %>
      			<%= f.text_area :comment, rows:'5', class: "form-control", placeholder: "コメントをここに" %>
  				<span><%= f.submit "送信", class: "btn btn-default pull-right" %></span>
			<% end %>
			</div>
	</div>
</div>