config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  
  get 'home/about' => 'home#about'
  get 'search' => 'search#search'
  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'users/sessions'}
  resources :users do
  	resource :relationships, only: [:create, :destroy]
  	get 'follows' => 'relationships#follow', as: 'follows'
  	get 'followers' => 'relationships#follower', as: 'followers'
  end
  resources :books do
  	resources :favorites, only: [:create]
    delete 'favorites' => 'favorites#destroy'
  	resources :book_comments, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	
	validates :title, presence: true
	validates :body, presence: true
	validates :body, length: {maximum: 200}

	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

	def Book.search(search, user_or_book, how_search)
		if user_or_book == "2"
			if how_search == "1"
				Book.where(['title LIKE ?', "%#{search}%"])
			elsif how_search == "2"
				Book.where(['title LIKE ?', "#{search}%"])
			elsif how_search == "3"
				Book.where(['title LIKE ?', "%#{search}"])
			elsif how_search == "4"
				Book.where(['title LIKE ?', "#{search}"])
			else
				Book.all
			end
		end
	end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	validates :comment, presence: true
	belongs_to :user
	belongs_to :book

end

app/models/favorite.rb
class Favorite < ApplicationRecord

	belongs_to :user
	belongs_to :book
	validates_uniqueness_of :book_id, scope: :user_id

end

app/models/relationship.rb
class Relationship < ApplicationRecord

	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  validates :introduction, length: {maximum: 50}
  validates :name, length: {minimum: 2, maximum: 20}, presence: true


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower

  attachment :profile_image

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

  def User.search(search, user_or_book, how_search)
    if user_or_book == "1"
      if how_search == "1"
        User.where(['name LIKE ?', "%#{search}%"])
      elsif how_search == "2"
        User.where(['name LIKE ?', "#{search}%"])
      elsif how_search == "3"
        User.where(['name LIKE ?', "%#{search}"])
      elsif how_search == "4"
        User.where(['name LIKE ?', "#{search}"])
      else
        User.all
      end
    end
  end

  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :postal_code, :prefecture_code, :city, :building])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile_image, :introduction])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!
  before_action :ensure_correct_book, {only: [:edit, :update, :destroy]}

  def index
  	@books = Book.all
    @user = User.find(current_user.id)
    @book = Book.new
  end

  def create
  	@book = Book.new(book_params)
    @book.user_id = current_user.id
    @user = User.find(current_user.id)
  	@books = Book.all
  	if @book.save
  		flash[:notice] = "You have creatad book successfully."
  		redirect_to book_path(@book.id)
  	else
  		render :index
  	end
  end

  def show
  	@book = Book.find(params[:id])
    @user = User.find(current_user.id)
    @book2 = Book.new
    @book_comment = BookComment.new
  end

  def edit
  	@book = Book.find(params[:id])
  end

  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		flash[:notice] = "You have updated book successfully."
  		redirect_to book_path(@book.id)
  	else
  		render :edit
  	end
  end

  def destroy
  	book = Book.find(params[:id])
  	book.destroy
  	redirect_to books_path
  end

  private

  def book_params
  	params.require(:book).permit(:title, :body, :user_id)
  end

  def ensure_correct_book
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

	def create
		@book = Book.find(params[:book_id])
		favorite = current_user.favorites.new(book_id: params[:book_id])
		favorite.save
	end

	def destroy
		@book = Book.find(params[:book_id])
		favorite = current_user.favorites.find_by(book_id: params[:book_id])
		favorite.destroy
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def top
  end

  def about
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
	def search
		@user_or_book = params[:option]
		@how_search = params[:choice]
		if @user_or_book == "1"
			@users = User.search(params[:search], @user_or_book, @how_search)
		else
			@books = Book.search(params[:search], @user_or_book, @how_search)
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  before_action :ensure_correct_user, {only: [:edit, :update]}

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
  	@book = Book.new
  end

  def index
  	@user = User.find(current_user.id)
  	@users = User.all
  	@book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       flash[:notice] = "You have updated user successfully."
       @user.save
       redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
  params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Booker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav class="navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to " Home", user_path(current_user.id), class:"glyphicon glyphicon-home" %></li>
              <li><%= link_to " Users", users_path, class:"glyphicon glyphicon-user" %></li>
              <li><%= link_to " Books", books_path, class:"glyphicon glyphicon-book" %></li>
              <li><%= link_to " logout", destroy_user_session_path, method: :delete, class:"glyphicon glyphicon-log-out" %></li>
            <% else %>
              <li><%= link_to " Home", root_path, class:"glyphicon glyphicon-home" %></li>
              <li><%= link_to " About", "/home/about", class:"glyphicon glyphicon-link" %></li>
              <li><%= link_to " Sign up", new_user_registration_path, class:"glyphicon glyphicon-edit" %></li>
              <li><%= link_to " login", new_user_session_path, class:"glyphicon glyphicon-log-in" %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <body>
      <% if current_user %>
      <div class="row">
          <div class="col-xs-7, col-xs-offset-5">
          <%= form_tag(search_path, :method => 'get') do %>
            <%= text_field_tag :search %>
            <%= select_tag(:option, options_for_select([["User", "1"],["Book", "2"]])) %>

            <%= select_tag(:choice, options_for_select([["部分一致", "1"],["前方一致", "2"],["後方一致", "3"],["完全一致", "4"]])) %>

            <%= submit_tag '検索' %>
          <% end %>
        </div>
      </div>
    <% end %>
    <%= yield %>
  </body>
  <footer>
    <div class="col-xs-3 col-xs-offset-9">
      <p>CopyRight Infratop.inc</p>
    </div>
  </footer>
  </body>
</html>